name: fdg2fmiso2
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python==3.8.19
- pytorch==1.8.1
- torchvision==0.9.1
- scipy
- numpy==1.19.2
- visdom
- wandb==0.12.18
- dominate==2.6.0
- pip
- pip:
  - "pyCERR[napari] @ git+https://github.com/cerr/pyCERR"
